import * as githubTestHelpers from '../../../tests/helpers/github'

describe('github test helpers', () => {
  describe('generateDetailedUserMock()', () => {
    it('should return a object properly configured with id argument given', () => {
      const id = 10
      const expectedUserStaticMock = {
        login: `login${id}`,
        id,
        avatar_url: `https://avatars1.githubusercontent.com/u/${id}?v=4`,

        name: `name${id}`,
        bio: `bio${id}`,
        public_repos: id,
        public_gists: id,
      }

      const newUserDetail = githubTestHelpers.generateDetailedUserMock(id)

      expect(newUserDetail).toStrictEqual(expectedUserStaticMock)
    })
  })

  describe('generateUserMock()', () => {
    it('should return an object properly configured', () => {
      const id = 10

      const expectedUserMock = {
        id,
        login: `login${id}`,
      }

      const newUserMock = githubTestHelpers.generateUserMock(id)

      expect(newUserMock).toStrictEqual(expectedUserMock)
    })
  })

  describe('generateUserBatchMock()', () => {
    it('should return a list of item generated by generateUserMock and properly configured', () => {
      const newUsersBatchMock = githubTestHelpers.generateUserBatchMock(0, 2)

      const expectedGenerateUserBatchMock = [
        {
          login: 'login1',
          id: 1,
        },
        {
          login: 'login2',
          id: 2,
        },
      ]

      expect(newUsersBatchMock).toStrictEqual(expectedGenerateUserBatchMock)
    })
  })
})
